logging:
    level.com.dih.connector.test: DEBUG
producer:
    username:
    password:
    baseUrl: https://catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com/producer
consumer:
    username:
    password:
    baseUrl: https://catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com/consumer
offerId: 40ba6117-c10e-4eb3-b4e2-9321e27286fc
test.mode: CONSUME